spring.profiles.active: develop
spring.main.allow-bean-definition-overriding: true

server.port: 8080

spring:
  application:
    name: sprint-service
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - ${KAFKA_HOST_PORT}
      bindings:
        output:
          destination: ${DESTINATION_CHANNEL}
          content-type: application/json
  data:
    mongodb:
      database: ${DB_NAME}
      uri: ${DB_URI}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}

event:
  publisher:
    poolSize: 1
    delay: 3000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS